linters-settings:
  errcheck:
    exclude-functions:
      - fmt:.*
      - io/ioutil:^Read.*

  goimports:
    local-prefixes: github.com/Mrs4s/go-cqhttp

  gocritic:
    disabled-checks:
      - exitAfterDefer

  forbidigo:
    # Forbid the following identifiers
    forbid:
      - ^fmt\.Errorf$ # consider errors.Errorf in github.com/pkg/errors

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  fast: false
  enable:
    - bodyclose
    - durationcheck
    - gofmt
    - goimports
    - errcheck
    - exportloopref
    - exhaustive
    - bidichk
    - gocritic
    - gosimple
    - govet
    - ineffassign
    #- nolintlint
    - staticcheck
    - stylecheck
    - unconvert
    - usestdlibvars
    - unparam
    - unused
    - whitespace
    - prealloc
    - predeclared
    - asciicheck
    - revive
    - forbidigo
    - makezero

run:
  # default concurrency is a available CPU number.
  # concurrency: 4 # explicitly omit this value to fully utilize available resources.
  timeout: 5m
  issues-exit-code: 1
  tests: true

# output configuration options
output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

issues:
  # Fix found issues (if it's supported by the linter)
  fix: true
  exclude-use-default: false
  exclude:
    - "Error return value of .((os.)?std(out|err)..*|.*Close|.*Seek|.*Flush|os.Remove(All)?|.*print(f|ln)?|os.(Un)?Setenv). is not check"
  exclude-dirs:
    - db
    - cmd/api-generator
    - internal/encryption
